//! Server-side library for the secure private messaging backend.
//!
//! Phase 2 intentionally limits server cryptography to public-key authentication
//! verification. Client private keys must never be transmitted to or generated by
//! this crate.

pub mod auth;
pub mod crypto;
